from app.legacy.mock_models import (
    MOCK_AI_BAD_RESPONSE,
    MOCK_AI_GOOD_RESPONSE,
    MOCK_CSS_BAD_RESPONSE,
    MOCK_CSS_GOOD_RESPONSE,
    MOCK_EMAIL_BAD_RESPONSE,
    MOCK_EMAIL_GOOD_RESPONSE,
    MOCK_FORMAT_BAD_RESPONSE,
    MOCK_MULTIPLY_BAD_RESPONSE,
    MOCK_MULTIPLY_GOOD_RESPONSE,
    MOCK_NOTABLE_QUOTES_BAD_RESPONSE,
    MOCK_NOTABLE_QUOTES_GOOD_RESPONSE,
    MOCK_STARTING_LINEUP_BAD_RESPONSE,
    MOCK_STARTING_LINEUP_GOOD_RESPONSE,
    MOCK_TIC_TAC_TOE_FULL_FILE_BAD_RESPONSE,
    MOCK_TIC_TAC_TOE_FULL_FILE_GOOD_RESPONSE,
)


REAL_GEMINI = "gemini-flash-latest"
REAL_GROQ = "groq:llama-3.3-70b-versatile"
REAL_MISTRAL = "mistral:mistral-small-latest"
ACTIVE_MODEL_IDS = [REAL_GEMINI, REAL_GROQ, REAL_MISTRAL]


def build_generate_solution_side_effect(response_map):
    def _side_effect(_problem_prompt: str, model_name: str) -> dict:
        if model_name not in response_map:
            raise ValueError(f"Unsupported model_name: {model_name}")
        return {
            "model_name": model_name,
            "raw_response": response_map[model_name],
        }

    return _side_effect


TWO_SUM_ACCEPTED_AND_FAILED = {
    REAL_GEMINI: MOCK_AI_GOOD_RESPONSE,
    REAL_GROQ: MOCK_AI_BAD_RESPONSE,
    REAL_MISTRAL: MOCK_AI_BAD_RESPONSE,
}

TWO_SUM_FORMAT_BAD = {
    REAL_GEMINI: MOCK_FORMAT_BAD_RESPONSE,
}

FIX_USER_EMAIL_ACCEPTED_AND_FAILED = {
    REAL_GEMINI: MOCK_EMAIL_GOOD_RESPONSE,
    REAL_GROQ: MOCK_EMAIL_BAD_RESPONSE,
    REAL_MISTRAL: MOCK_EMAIL_BAD_RESPONSE,
}

MULTIPLY_ACCEPTED_AND_FAILED = {
    REAL_GEMINI: MOCK_MULTIPLY_GOOD_RESPONSE,
    REAL_GROQ: MOCK_MULTIPLY_BAD_RESPONSE,
    REAL_MISTRAL: MOCK_MULTIPLY_BAD_RESPONSE,
}

CSS_REGION_ACCEPTED_AND_FAILED = {
    REAL_GEMINI: MOCK_CSS_GOOD_RESPONSE,
    REAL_GROQ: MOCK_CSS_BAD_RESPONSE,
    REAL_MISTRAL: MOCK_CSS_BAD_RESPONSE,
}

STARTING_LINEUP_ACCEPTED_AND_FAILED = {
    REAL_GEMINI: MOCK_STARTING_LINEUP_GOOD_RESPONSE,
    REAL_GROQ: MOCK_STARTING_LINEUP_BAD_RESPONSE,
    REAL_MISTRAL: MOCK_STARTING_LINEUP_BAD_RESPONSE,
}

TIC_TAC_TOE_ACCEPTED_AND_FAILED = {
    REAL_GEMINI: MOCK_TIC_TAC_TOE_FULL_FILE_GOOD_RESPONSE,
    REAL_GROQ: MOCK_TIC_TAC_TOE_FULL_FILE_BAD_RESPONSE,
    REAL_MISTRAL: MOCK_TIC_TAC_TOE_FULL_FILE_BAD_RESPONSE,
}

NOTABLE_QUOTES_ACCEPTED_AND_FAILED = {
    REAL_GEMINI: MOCK_NOTABLE_QUOTES_GOOD_RESPONSE,
    REAL_GROQ: MOCK_NOTABLE_QUOTES_BAD_RESPONSE,
    REAL_MISTRAL: MOCK_NOTABLE_QUOTES_BAD_RESPONSE,
}
